### PR TITLE
Changes to runtime settings handling

### PR DESCRIPTION
**Pull request by pb66**
Default settings initially loaded prior to set() loop so they are not logged as changes and advertised.
Changes to RFM settings are checked & discarded if not valid, the service codes are also logged
couple of minor changes see commits for detail

### CODE REVIEW

**Comment by lafrech** [comment]
I don't think it hurts to print the default values in the log. It may be redundant, but not an issue. It may even be useful if the default values change from one version to another.

**Comment by pb66** [comment]
If a default setting is changed even during set up it will be logged, the suppression of defaults was more to silence unused options like pause/interval etc. But it has been in such a way that the full list of options can be output by removing/commenting one line if that's the preference.

**Comment by lafrech** [comment]
I might not be relevant on this (and I still need to read a lot of messages and get back to my Pi, update and test).

Ideally, I'd rather have too much information in the logs (can't hurt) and rely only on logging level for the filtering.

I mean if the typical use case is a user posting on the forum to solve an issue, we want to have every information we might need in the first post. Asking him to use DEBUG logging level should be enough (rather than commenting a line, etc.).

Again, that was just a thought.

**Comment by pb66** [comment]
Sorry I'm not explaining very well. When I say a line could be deleted or commented out I meant by us whilst developing not by a user. If we decide to change approach or not it's easy to accommodate either way, just one line for us to change.

Regards log entries when the appropriate level is set any changes made are logged. All the one line does is stop the unused or unchanged defaults being logged at creation, since they are defaults we already know what they are if they remain unchanged and unlogged.

**Pull request merged**
