### PR TITLE
Node decoding + Threading + Bulk upload

### PR DESCRIPTION
**Pull request by TrystanLea**
A start on adding threading to emonhub. This works with one dispatcher at the moment as I think it needs either a queue for each dispatcher or a pub/sub queue that handles this for us.  At the moment I think the queue will share the data between dispatchers rather than duplicate the data which is the behaviour we want.

This pull request contains the node_decoder pull request too.

### CODE REVIEW

**Comment by TrystanLea** [comment]
Ok, Im quite happy with this now, from brief testing its a working solution for:
- Flexible decoding (probably best to discuss separately as part of the other pull request)
- Threading so that data gaps are not created when a remote server is timing out, dispatching happens in its own thread separate from the listeners with a queue that links them.
- Buffering and bulk sending: when a server cannot be reached the data is buffered as existing implementation but when the connection resumes a full bulk upload happens of all the data in one request rather than many individual requests. The bulk data is also sent in the body of a post request.

Im quite new to Python so interested to hear your more experienced thoughts on it.

**Comment by TrystanLea** [comment]
Latest commit which I've bundled in here:
- Allows for different default decoding types
- Allows for posting to different emoncms interfaces ie: input/bulk or node/multiple with a simple settings property.
- These relatively small changes give full compatibility with remote based emoncms node interface if application needs this approach without bulking out emonhub with code duplication

**Comment by Dave-McCraw** [comment]
This is tricky for me to review. It would be helpful if we could break it down into separate pull requests:
- refactor without adding node support
- addition of node support
- addition of multithreading

(I guess the last one could come in any order, whatever is most convenient. I'm slightly nervous about multithreading it "just like that" because I have plenty of experience of multithreading agony, maybe I'm being overly pessimistic!)

**Comment by Dave-McCraw** [comment]
In fact, is there even a fourth thing in here? Just forwarding on the bytes?

I'll pick this up in #22 too

**Comment by TrystanLea** [comment]
I've separated out the node decoding and bulk upload leaving the changes for threading only https://github.com/emonhub/emonhub/pull/34/files

**Comment by TrystanLea** [comment]
Added the ability to set the max number of items that can be posted in one bulk upload, so that under conditions where the internet has been down for an extended time it doesnt try and send too much at once, if say emoncms.org is down for a day and hundreds of connected rpi's try and upload at once it might be too much, so this makes it possible to stage the upload.

**Comment by TrystanLea** [comment]
Glyn and I are now testing this in our own homes on test systems to test its long term reliability. Will also try some tests with unplugging the ethernet for a few hours to see how well it posts the buffered data.

**Comment by pb66** [comment]
(just for ref) http://openenergymonitor.org/emon/node/5239

**Comment by TrystanLea** [comment]
Closing as node decoding and bulk upload is now done very nicely by @pb66's emonhub developments and I've opened another pull request with threading additions only.

**Pull request closed without merging**
