### PR TITLE
Threading Only

### PR DESCRIPTION
**Pull request by TrystanLea**
Pull request with only the changes that run the dispatchers in their own threads

### CODE REVIEW

**Comment by Dave-McCraw** [comment]
OK, thanks - I'll need to have a play with this but it looks much easier to follow :)

**Comment by TrystanLea** [comment]
Thanks, let me know if I can help with anything.

**Comment by Dave-McCraw** [comment]
Will do. Just to let you know I'm heading off for a long weekend, so I won't be able to get back to you until next week :)

**Comment by TrystanLea** [comment]
Replaced with https://github.com/emonhub/emonhub/pull/67

**Pull request closed without merging**
