### PR TITLE
Added threading to dispatchers

### PR DESCRIPTION
**Pull request by pb66**
Threading added so that each dispatcher created in it's own thread to
prevent "timeouts" due to network or server issues causing emonHub to
"wait" and potentially miss incoming packets.

### CODE REVIEW

**Comment by pb66** [comment]
@TrystanLea, Please take a look at this it's pretty similar to your version but with the start() moved and the pause/interval stuff done.

**Comment by TrystanLea** [comment]
Great, that looks good. Does:
    del(self._dispatchers[name])
in update settings stop the thread ok, i guess it does?

**Comment by TrystanLea** [comment]
Checking that in my mini example, del by itself doesnt stop the thread, setting the stop variable before deleting worked:

```
self._dispatchers[name].stop = True;
del(self._dispatchers[name])
```

**Comment by pb66** [comment]
your right the thread didn't get deleted with the dispatcher but your additional line fixes that, thanks

**Comment by pb66** [comment]
This discussion continues in #66

**Pull request merged**
