### PR TITLE
Logging level setting

### PR DESCRIPTION
**Pull request by pb66**
Loglevel is no longer a compulsory setting, if omited or incorrect the
default level of "WARNING" is used, this includes start up and runtime
setting edits. it is no longer case sensitive, At start up the version
and "starting hub..." are always logged at start up now regardless of
level set.

### CODE REVIEW

**Comment by pb66** [comment]
Another step towards making emonHub s robust as possible

**Comment by lafrech** [comment]
Shouldn't the default be CRITICAL so as to avoid writing to the SD card ?

Or is there a specific config file for the read-only version ?

**Comment by TrystanLea** [comment]
Hello Jerome!, the log files write to a tmpfs in ram so its not such an issue. Im not sure if there needs to be some way of setting a maximum limit for the log files to avoid taking up to much ram?

**Comment by pb66** [comment]
I think the log files are limited by the size of the file created in RAM during boot, the fstan entry has a size=30M entry also I believe the logger is set to rotate 2 files of upto 5mb.

```
tmpfs           /var/log        tmpfs   nodev,nosuid,size=30M,mode=1777       0    0
```

I actually pondered on making the default debug so that if there is any uncertainty at least the log could  explain rather than no log enties and not knowing why, but guessed the shipped entry in the conf file would clarify maybe.

**Comment by lafrech** [comment]
OK fine. So I suppose it is logged on the hard drive if there is one and in RAM if using light read-only mode.

Log files are limited in size already:

https://github.com/emonhub/emonhub/blob/development/src/emonhub.py#L258

**Comment by lafrech** [comment]
In an ideal world, DEBUG is for devs only, and WARNING is fine.

Let's pretend for a while we're in an ideal world.

**Pull request merged**
