### PR TITLE
Serial baud rate setting

### PR DESCRIPTION
**Pull request by pb66**
Added an optional setting for baud rate. if omitted the default value hardcoded in the respective listener will be used and if the passed value (setting or default) is not on the "common values" list then it will default to 9600.

### CODE REVIEW

**Comment by pb66** [comment]
As mentioned https://github.com/Jerome-github/oem_gateway/issues/16 and on OEM forum, the baud rate should be a configuration setting. This should be of value for serial reader type listeners ( #40 and #36 ) and also for RFM69

**Comment by lafrech** [comment]
> Added an optional setting for baud rate.

Great.

> if the passed value (setting or default) is not on the "common values" list then it will default to 9600

Not sure this is useful. In case of typo, an error will immediately lead the user to change the value he entered. Nothing indicates 9600 is the proper one anyway.

Besides, I have no experience there, but if there was an exotic device with a value out of [75, 110, 300, 1200, 2400, 4800, 9600, 19200, 38400, 57600, 115200], this test would get in the way.

(Sorry about arguing on details. I should mention you did quite a lot of great work.)

**Comment by pb66** [comment]
Thanks for taking the time to read all this and give your feedback, good or bad it's good to hear.

The main reason behind default values is to get emonhub to start and continue to run no matter what so that remote access didn't trip over because emonhub needs restarting. Maybe escalating the log to warning or critical will draw users attention?

**Comment by lafrech** [comment]
OK, I understand the idea.

In fact, if a wrong baud rate is set, the interface probably won't receive anything, but I don't expect a crash (see http://pyserial.sourceforge.net/pyserial_api.html).

I didn't find a way to set logging ON or OFF, but we don't use critical level, so settings log level to CRITICAL means no log is written. Setting WARNING means we get warnings and errors.

I didn't see anything about remote control yet, but it would be nice to have the logs accessible from where EmonHub is being controled. If this is the case, then the baud rate error (or any other) is made visible to the user.

**Comment by pb66** [comment]
No I don't think it would crash but it won't start or create interfacer without an init_setting to pass to the **init** so unless we include a default value emonhub must be restarted after adding a value for com_baud in init_settings.

My ref to escalating to warning or critical was so that it get logged no matter what level set and is easier to pick out if a low loglevel set.

The remote access idea is only being experimented with at the moment I don't have all the elements yet but the concept is #64, It would be a great idea to be able to access the logfile, I assumed some sort of acknowledgement would be put in place but using the log entries would be far more useful.

**Comment by lafrech** [comment]
> No I don't think it would crash but it won't start or create interfacer without an init_setting to pass to the init so unless we include a default value emonhub must be restarted after adding a value for com_baud in init_settings.

Yes sure. A default is nice. I'm just saying enforcing a value in this set of common values is superfluous (and could even be problematic in exotic cases that will never happen).

> My ref to escalating to warning or critical was so that it get logged no matter what level set and is easier to pick out if a low loglevel set.

Ah ok. I misunderstood that. I think INFO is nice for "open com port with baudrate 69000". Maybe a warning if the value is uncommon ?

> It would be a great idea to be able to access the logfile, I assumed some sort of acknowledgement would be put in place but using the log entries would be far more useful.

Yes. I don't know if it would be difficult but it definitely would be great.

**Comment by pb66** [comment]
I've thought about the "list" and see both arguments for and against (as seems to be the case for all current decisions) I think we could change it down line if it's an issue but for now I'd like to keep it.

I have found it very useful in recent weeks as when setting up new settings files I occasionally set the baud to 57400 rather than 57600 (for the rfm69) and emonhub tells me it's a invalid value rather than having to figure out why I'm not getting any data.

The more exotic values I agree could cause a problem but I feel they are more likely to be used by users capable of editing the list and submitting a pull request.

**Pull request merged**
